### ISSUE TITLE
db using float for monetary fields

### ISSUE THREAD

**Issue by twdamhore** [numedik/nmcore#3]
need to change it:
http://www.postgresql.org/docs/9.2/static/datatype-money.html
"Floating point numbers should not be used to handle money due to the potential for rounding errors."

**Comment by intelli7** [comment]
so we decide to use money on postgres?

**Comment by twdamhore** [comment]
i vote for money

**Comment by intelli7** [comment]
others? @nullify.e @jimanx2  @rainprecious ?

**Comment by rainprecious** [comment]
money

**Comment by intelli7** [comment]
@nullifye

**Comment by jimanx2** [comment]
+1 Money
http://www.postgresql.org/docs/9.1/static/datatype-money.html
